#**Kerem Aksoy**
#HomeWork 2 : Naive Bayes' Classifier

Importing the necessary libraries:

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

Importing the dataset:

In [ ]:
data_setY =np.genfromtxt("hw02_labels.csv",delimiter = ",")

In [ ]:
data_setX=np.genfromtxt("hw02_images.csv", delimiter = ",")


Splitting the set into traning and test set

In [ ]:
x_train = data_setX[:30000,:]
y_train = data_setY[:30000]

x_test = data_setX[30000:,:]
y_test = data_setY[30000:]


Finding prior probabilites for classes


In [ ]:
class_priors = [0,0,0,0,0] #This will hold number of examples which belongs to each class
totalNumber = len(y_train)
for i in range(1,6):
  temp = y_train[y_train == i]
  class_priors [i-1] = len(temp) / totalNumber

Finding the means values of 5 classes for each feature 

In [ ]:
means = []
for i in range(1,6):
  temp = x_train[y_train == i]
  temp_list = temp.mean(axis=0)
  means.append(temp_list)
sample_means = np.array(means)

Finding derivations

In [ ]:
deviations = []
for i in range(1,6):
  temp = np.sqrt(np.mean((x_train[y_train == i]-sample_means[i-1])**2,axis=0))
  deviations.append(temp)
sample_deviations = np.array(deviations)


Creating the posterier probabilty finder function

In [ ]:
import math
#In this function, after calculating the value, I take the maximum probability label to choose which one
#This fuction returns the label which x belongs to given x
def findPosterior_andDecide(x):
    scoreList = []
    for i in range(1,6):
      temp_prob = sum((-0.5*np.log(2*math.pi)) - (np.log(sample_deviations[i-1])) - ((x-sample_means[i-1])*(x-sample_means[i-1])/(2*sample_deviations[i-1]*sample_deviations[i-1]))) + class_priors[i-1] 
      scoreList.append(temp_prob)
    max_prob = max(scoreList)
    predicted_label = scoreList.index(max_prob) + 1 #Since our labels starst from 1 to 5
    return predicted_label

Now we need to generate confusion matrix to see the succes of the model for both training and test sets

Confusion Matrix For Training

In [ ]:
f = lambda x: findPosterior_andDecide(x) #Creating Lambda Experession
#This expression will be used to calculate the prediction for each row(example/point) in the training and test set.

In [ ]:
f = lambda x: findPosterior_andDecide(x)
training_predict = np.apply_along_axis(f,1,x_train)
confusionMatrixTest = confusion_matrix(training_predict,y_train)
print(confusionMatrixTest)

[[3685   49    4  679    6]
 [1430 5667 1140 1380  532]
 [ 508  208 4670 2948  893]
 [ 234   60  123  687  180]
 [ 143   16   63  306 4389]]


Confision Matrix For Testing

In [ ]:
test_predict = np.apply_along_axis(f,1,x_test)
confusionMatrixTest = np.array(confusion_matrix(test_predict,y_test))
print(confusionMatrix)

[[597   6   0 114   1]
 [237 955 188 267  81]
 [ 92  25 785 462 167]
 [ 34  11  16 109  29]
 [ 40   3  11  48 722]]
